name: check
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0"
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run check
