name: check-httpd-api-unit-test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-httpd-api-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm ci
      - name: Start http-api test server
        run: |
          mkdir -p tests/artifacts;
          ./scripts/run-httpd-with-fixtures --non-interactive --download 2>&1 | tee tests/artifacts/httpd-api.log &
      - run: npm run test:httpd-api:unit
