name: check-e2e
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-e2e:
    continue-on-error: true
    strategy:
      matrix:
        browser: [chromium, firefox]
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"

      - name: Install dependencies
        run: npm ci

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        id: playwright-dep-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}

      - name: Install Playwright browsers
        if: steps.playwright-dep-cache.outputs.cache-hit != 'true'
        run: npx playwright install chromium firefox

      - name: Install Radicle binaries
        run: |
          mkdir -p tests/artifacts;
          ./scripts/install-binaries;
          ./scripts/install-binaries --show-path >> $GITHUB_PATH;

      - name: Run Playwright tests
        run: |
          npm run test:e2e -- --project ${{ matrix.browser }};
          npm run test:e2e:ipfs -- --project ${{ matrix.browser }};

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-artifacts-${{ runner.os }}
          retention-days: 30
          if-no-files-found: "ignore"
          path: |
            tests/artifacts/**/*
