name: check-unit-test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm run test:unit
