name: check-radicle-httpd
on: push

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./radicle-httpd
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: radicle-httpd -> target
      - name: Build
        run: cargo build --all-features
        env:
          RUSTFLAGS: -D warnings
      - name: Run tests
        run: cargo test --all-features
  docs:
    name: Docs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./radicle-httpd
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: radicle-httpd -> target
      - name: Docs
        run: cargo doc --all-features
        env:
          RUSTDOCFLAGS: -D warnings
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./radicle-httpd
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: radicle-httpd -> target
      - name: Run clippy
        run: cargo clippy --tests
        env:
          RUSTFLAGS: -D warnings
      - name: Check formatting
        run: cargo fmt -- --check
